---
- hosts: all
  become: yes
  tasks: 
  - name: in this task i want to install webserver
    apt: 
      name: apache2
      state: present 
  - name: in this task i want to start webserver
    service:
      name: apache2
      state: started
  - name: in this task i want to install tree
    apt: 
      name: tree
      state: present 
  - name: in this task i want to install git
    apt: 
      name: git
      state: present